/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.libtorrent.swig;

public class dht_put_alert extends alert {
  private long swigCPtr;

  protected dht_put_alert(long cPtr, boolean cMemoryOwn) {
    super(libtorrent_jni.dht_put_alert_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dht_put_alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_dht_put_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String message() {
    return libtorrent_jni.dht_put_alert_message(swigCPtr, this);
  }

  public void setTarget(sha1_hash value) {
    libtorrent_jni.dht_put_alert_target_set(swigCPtr, this, sha1_hash.getCPtr(value), value);
  }

  public sha1_hash getTarget() {
    long cPtr = libtorrent_jni.dht_put_alert_target_get(swigCPtr, this);
    return (cPtr == 0) ? null : new sha1_hash(cPtr, false);
  }

  public void setPublic_key(SWIGTYPE_p_boost__arrayT_char_32_t value) {
    libtorrent_jni.dht_put_alert_public_key_set(swigCPtr, this, SWIGTYPE_p_boost__arrayT_char_32_t.getCPtr(value));
  }

  public SWIGTYPE_p_boost__arrayT_char_32_t getPublic_key() {
    return new SWIGTYPE_p_boost__arrayT_char_32_t(libtorrent_jni.dht_put_alert_public_key_get(swigCPtr, this), true);
  }

  public void setSignature(SWIGTYPE_p_boost__arrayT_char_64_t value) {
    libtorrent_jni.dht_put_alert_signature_set(swigCPtr, this, SWIGTYPE_p_boost__arrayT_char_64_t.getCPtr(value));
  }

  public SWIGTYPE_p_boost__arrayT_char_64_t getSignature() {
    return new SWIGTYPE_p_boost__arrayT_char_64_t(libtorrent_jni.dht_put_alert_signature_get(swigCPtr, this), true);
  }

  public void setSalt(String value) {
    libtorrent_jni.dht_put_alert_salt_set(swigCPtr, this, value);
  }

  public String getSalt() {
    return libtorrent_jni.dht_put_alert_salt_get(swigCPtr, this);
  }

  public void setSeq(java.math.BigInteger value) {
    libtorrent_jni.dht_put_alert_seq_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSeq() {
    return libtorrent_jni.dht_put_alert_seq_get(swigCPtr, this);
  }

}
