/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.libtorrent.swig;

public class SWIGTYPE_p_boost__tupleT_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v4_t_t_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v6_t_t_t {
  private long swigCPtr;

  protected SWIGTYPE_p_boost__tupleT_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v4_t_t_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v6_t_t_t(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_boost__tupleT_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v4_t_t_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v6_t_t_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_boost__tupleT_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v4_t_t_std__vectorT_libtorrent__ip_rangeT_boost__asio__ip__address_v6_t_t_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

