/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class cached_piece_info_vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cached_piece_info_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cached_piece_info_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_cached_piece_info_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public cached_piece_info_vector() {
    this(libtorrent_jni.new_cached_piece_info_vector(), true);
  }

  public long size() {
    return libtorrent_jni.cached_piece_info_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libtorrent_jni.cached_piece_info_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtorrent_jni.cached_piece_info_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtorrent_jni.cached_piece_info_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtorrent_jni.cached_piece_info_vector_clear(swigCPtr, this);
  }

  public void add(cached_piece_info x) {
    libtorrent_jni.cached_piece_info_vector_add(swigCPtr, this, cached_piece_info.getCPtr(x), x);
  }

  public cached_piece_info get(int i) {
    return new cached_piece_info(libtorrent_jni.cached_piece_info_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, cached_piece_info val) {
    libtorrent_jni.cached_piece_info_vector_set(swigCPtr, this, i, cached_piece_info.getCPtr(val), val);
  }

}
