/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class disk_buffer_holder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected disk_buffer_holder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(disk_buffer_holder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_disk_buffer_holder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public disk_buffer_holder(SWIGTYPE_p_libtorrent__aux__session_impl ses, String buf) {
    this(libtorrent_jni.new_disk_buffer_holder__SWIG_0(SWIGTYPE_p_libtorrent__aux__session_impl.getCPtr(ses), buf), true);
  }

  public disk_buffer_holder(disk_buffer_pool disk_pool, String buf) {
    this(libtorrent_jni.new_disk_buffer_holder__SWIG_1(disk_buffer_pool.getCPtr(disk_pool), disk_pool, buf), true);
  }

  public String release() {
    return libtorrent_jni.disk_buffer_holder_release(swigCPtr, this);
  }

  public String get() {
    return libtorrent_jni.disk_buffer_holder_get(swigCPtr, this);
  }

  public void reset(String buf) {
    libtorrent_jni.disk_buffer_holder_reset__SWIG_0(swigCPtr, this, buf);
  }

  public void reset() {
    libtorrent_jni.disk_buffer_holder_reset__SWIG_1(swigCPtr, this);
  }

  public void swap(disk_buffer_holder h) {
    libtorrent_jni.disk_buffer_holder_swap(swigCPtr, this, disk_buffer_holder.getCPtr(h), h);
  }

}
