/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class hash_failed_alert extends torrent_alert {
  private long swigCPtr;

  protected hash_failed_alert(long cPtr, boolean cMemoryOwn) {
    super(libtorrent_jni.hash_failed_alert_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(hash_failed_alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_hash_failed_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public hash_failed_alert(torrent_handle h, int index) {
    this(libtorrent_jni.new_hash_failed_alert(torrent_handle.getCPtr(h), h, index), true);
  }

  public int type() {
    return libtorrent_jni.hash_failed_alert_type(swigCPtr, this);
  }

  public int category() {
    return libtorrent_jni.hash_failed_alert_category(swigCPtr, this);
  }

  public String what() {
    return libtorrent_jni.hash_failed_alert_what(swigCPtr, this);
  }

  public String message() {
    return libtorrent_jni.hash_failed_alert_message(swigCPtr, this);
  }

  public void setPiece_index(int value) {
    libtorrent_jni.hash_failed_alert_piece_index_set(swigCPtr, this, value);
  }

  public int getPiece_index() {
    return libtorrent_jni.hash_failed_alert_piece_index_get(swigCPtr, this);
  }

  public final static int alert_type = libtorrent_jni.hash_failed_alert_alert_type_get();
  public final static int static_category = libtorrent_jni.hash_failed_alert_static_category_get();
}
