/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class ipv6_peer extends torrent_peer {
  private long swigCPtr;

  protected ipv6_peer(long cPtr, boolean cMemoryOwn) {
    super(libtorrent_jni.ipv6_peer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ipv6_peer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_ipv6_peer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ipv6_peer(tcp_endpoint ip, boolean connectable, int src) {
    this(libtorrent_jni.new_ipv6_peer(tcp_endpoint.getCPtr(ip), ip, connectable, src), true);
  }

}
