/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class scrape_reply_alert extends tracker_alert {
  private long swigCPtr;

  protected scrape_reply_alert(long cPtr, boolean cMemoryOwn) {
    super(libtorrent_jni.scrape_reply_alert_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(scrape_reply_alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_scrape_reply_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public scrape_reply_alert(torrent_handle h, int incomp, int comp, String u) {
    this(libtorrent_jni.new_scrape_reply_alert(torrent_handle.getCPtr(h), h, incomp, comp, u), true);
  }

  public int type() {
    return libtorrent_jni.scrape_reply_alert_type(swigCPtr, this);
  }

  public int category() {
    return libtorrent_jni.scrape_reply_alert_category(swigCPtr, this);
  }

  public String what() {
    return libtorrent_jni.scrape_reply_alert_what(swigCPtr, this);
  }

  public String message() {
    return libtorrent_jni.scrape_reply_alert_message(swigCPtr, this);
  }

  public void setIncomplete(int value) {
    libtorrent_jni.scrape_reply_alert_incomplete_set(swigCPtr, this, value);
  }

  public int getIncomplete() {
    return libtorrent_jni.scrape_reply_alert_incomplete_get(swigCPtr, this);
  }

  public void setComplete(int value) {
    libtorrent_jni.scrape_reply_alert_complete_set(swigCPtr, this, value);
  }

  public int getComplete() {
    return libtorrent_jni.scrape_reply_alert_complete_get(swigCPtr, this);
  }

  public final static int alert_type = libtorrent_jni.scrape_reply_alert_alert_type_get();
}
