/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class session_stats_alert extends alert {
  private long swigCPtr;

  protected session_stats_alert(long cPtr, boolean cMemoryOwn) {
    super(libtorrent_jni.session_stats_alert_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(session_stats_alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_session_stats_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public session_stats_alert() {
    this(libtorrent_jni.new_session_stats_alert(), true);
  }

  public int type() {
    return libtorrent_jni.session_stats_alert_type(swigCPtr, this);
  }

  public int category() {
    return libtorrent_jni.session_stats_alert_category(swigCPtr, this);
  }

  public String what() {
    return libtorrent_jni.session_stats_alert_what(swigCPtr, this);
  }

  public String message() {
    return libtorrent_jni.session_stats_alert_message(swigCPtr, this);
  }

  public boolean discardable() {
    return libtorrent_jni.session_stats_alert_discardable(swigCPtr, this);
  }

  public void setTimestamp(java.math.BigInteger value) {
    libtorrent_jni.session_stats_alert_timestamp_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTimestamp() {
    return libtorrent_jni.session_stats_alert_timestamp_get(swigCPtr, this);
  }

  public void setValues(uint64_vector value) {
    libtorrent_jni.session_stats_alert_values_set(swigCPtr, this, uint64_vector.getCPtr(value), value);
  }

  public uint64_vector getValues() {
    long cPtr = libtorrent_jni.session_stats_alert_values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new uint64_vector(cPtr, false);
  }

  public final static int alert_type = libtorrent_jni.session_stats_alert_alert_type_get();
  public final static int static_category = libtorrent_jni.session_stats_alert_static_category_get();
}
