/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class SWIGTYPE_p_libtorrent__dht_lookup {
  private long swigCPtr;

  protected SWIGTYPE_p_libtorrent__dht_lookup(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_libtorrent__dht_lookup() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_libtorrent__dht_lookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

