package com.frostwire.jlibtorrent.alerts;

import com.frostwire.jlibtorrent.swig.*;

/**
 * @author gubatron
 * @author aldenml
 */
public enum AlertType {

    TORRENT(torrent_alert.alert_type),
    PEER(peer_alert.alert_type),
    TRACKER(tracker_alert.alert_type),
    TORRENT_ADDED(torrent_added_alert.alert_type),
    TORRENT_FINISHED(torrent_finished_alert.alert_type),
    TORRENT_REMOVED(torrent_removed_alert.alert_type),
    TORRENT_UPDATE(torrent_update_alert.alert_type),
    TORRENT_DELETED(torrent_deleted_alert.alert_type),
    TORRENT_PAUSED(torrent_paused_alert.alert_type),
    TORRENT_RESUMED(torrent_resumed_alert.alert_type),
    TORRENT_CHECKED(torrent_checked_alert.alert_type),
    TORRENT_ERROR(torrent_error_alert.alert_type),
    TORRENT_NEED_CERT(torrent_need_cert_alert.alert_type),
    INCOMING_CONNECTION(incoming_connection_alert.alert_type),
    ADD_TORRENT(add_torrent_alert.alert_type),
    SAVE_RESUME_DATA(save_resume_data_alert.alert_type),
    FASTRESUME_REJECTED(fastresume_rejected_alert.alert_type),
    BLOCK_FINISHED(block_finished_alert.alert_type),
    METADATA_RECEIVED(metadata_received_alert.alert_type),
    METADATA_FAILED(metadata_failed_alert.alert_type),
    FILE_COMPLETED(file_completed_alert.alert_type),
    FILE_RENAMED(file_renamed_alert.alert_type),
    FILE_RENAME_FAILED(file_rename_failed_alert.alert_type),
    FILE_ERROR(file_error_alert.alert_type),
    HASH_FAILED(hash_failed_alert.alert_type),
    PORTMAP(portmap_alert.alert_type),
    PORTMAP_ERROR(portmap_error_alert.alert_type),
    PORTMAP_LOG(portmap_log_alert.alert_type),
    TRACKER_ANNOUNCE(tracker_announce_alert.alert_type),
    TRACKER_REPLY(tracker_reply_alert.alert_type),
    TRACKER_WARNING(tracker_warning_alert.alert_type),
    TRACKER_ERROR(tracker_error_alert.alert_type),
    READ_PIECE(read_piece_alert.alert_type),
    STATE_CHANGED(state_changed_alert.alert_type),
    DHT_REPLY(dht_reply_alert.alert_type),
    DHT_BOOTSTRAP(dht_bootstrap_alert.alert_type),
    DHT_GET_PEERS(dht_get_peers_alert.alert_type),
    EXTERNAL_IP(external_ip_alert.alert_type),
    LISTEN_SUCCEEDED(listen_succeeded_alert.alert_type),
    STATE_UPDATE(state_update_alert.alert_type),
    MMAP_CACHE(mmap_cache_alert.alert_type),
    SESSION_STATS(session_stats_alert.alert_type),
    SCRAPE_REPLY(scrape_reply_alert.alert_type),
    SCRAPE_FAILED(scrape_failed_alert.alert_type),
    LSD_PEER(lsd_peer_alert.alert_type),
    PEER_BLOCKED(peer_blocked_alert.alert_type),
    PERFORMANCE(performance_alert.alert_type),
    PIECE_FINISHED(piece_finished_alert.alert_type),
    SAVE_RESUME_DATA_FAILED(save_resume_data_failed_alert.alert_type),
    STATS(stats_alert.alert_type),
    STORAGE_MOVED(storage_moved_alert.alert_type),
    TORRENT_DELETE_FAILED(torrent_delete_failed_alert.alert_type),
    URL_SEED(url_seed_alert.alert_type),
    INVALID_REQUEST(invalid_request_alert.alert_type),
    LISTEN_FAILED(listen_failed_alert.alert_type),
    PEER_BAN(peer_ban_alert.alert_type),
    PEER_CONNECT(peer_connect_alert.alert_type),
    PEER_DISCONNECTED(peer_disconnected_alert.alert_type),
    PEER_ERROR(peer_error_alert.alert_type),
    PEER_SNUBBED(peer_snubbed_alert.alert_type),
    PEER_UNSNUBBED(peer_unsnubbed_alert.alert_type),
    REQUEST_DROPPED(request_dropped_alert.alert_type),
    UDP_ERROR(udp_error_alert.alert_type),
    ANONYMOUS_MODE(anonymous_mode_alert.alert_type),
    BLOCK_DOWNLOADING(block_downloading_alert.alert_type),
    BLOCK_TIMEOUT(block_timeout_alert.alert_type),
    CACHE_FLUSHED(cache_flushed_alert.alert_type),
    DHT_ANNOUNCE(dht_announce_alert.alert_type),
    STORAGE_MOVED_FAILED(storage_moved_failed_alert.alert_type),
    TRACKERID(trackerid_alert.alert_type),
    UNWANTED_BLOCK(unwanted_block_alert.alert_type),
    DHT_ERROR(dht_error_alert.alert_type),
    DHT_PUT(dht_put_alert.alert_type),
    DHT_MUTABLE_ITEM(dht_mutable_item_alert.alert_type),
    DHT_IMMUTABLE_ITEM(dht_immutable_item_alert.alert_type),
    I2P(i2p_alert.alert_type),
    DHT_OUTGOING_GET_PEERS(dht_outgoing_get_peers_alert.alert_type),
    LOG(log_alert.alert_type),
    TORRENT_LOG(torrent_log_alert.alert_type),
    PEER_LOG(peer_log_alert.alert_type),
    LSD_ERROR(lsd_error_alert.alert_type),
    DHT_STATS(dht_stats_alert.alert_type),
    INCOMING_REQUEST(incoming_request_alert.alert_type),
    DHT_LOG(dht_log_alert.alert_type),
    DHT_PKT(dht_pkt_alert.alert_type),
    DHT_GET_PEERS_REPLY(dht_get_peers_reply_alert.alert_type),
    DHT_DIRECT_RESPONSE(dht_direct_response_alert.alert_type),
    PICKER_LOG(picker_log_alert.alert_type),
    UNKNOWN(-1),
    TORRENT_PRIORITIZE(-2);

    private static AlertType[] ALERT_TYPES = {
                       TORRENT,
                       PEER,
                       TRACKER,
                       TORRENT_ADDED,
                       TORRENT_REMOVED,
                       READ_PIECE,
                       FILE_COMPLETED,
                       FILE_RENAMED,
                       FILE_RENAME_FAILED,
                       PERFORMANCE,
                       STATE_CHANGED,
                       TRACKER_ERROR,
                       TRACKER_WARNING,
                       SCRAPE_REPLY,
                       SCRAPE_FAILED,
                       TRACKER_REPLY,
                       DHT_REPLY,
                       TRACKER_ANNOUNCE,
                       HASH_FAILED,
                       PEER_BAN,
                       PEER_UNSNUBBED,
                       PEER_SNUBBED,
                       PEER_ERROR,
                       PEER_CONNECT,
                       PEER_DISCONNECTED,
                       INVALID_REQUEST,
                       TORRENT_FINISHED,
                       PIECE_FINISHED,
                       REQUEST_DROPPED,
                       BLOCK_TIMEOUT,
                       BLOCK_FINISHED,
                       BLOCK_DOWNLOADING,
                       UNWANTED_BLOCK,
                       STORAGE_MOVED,
                       STORAGE_MOVED_FAILED,
                       TORRENT_DELETED,
                       TORRENT_DELETE_FAILED,
                       SAVE_RESUME_DATA,
                       SAVE_RESUME_DATA_FAILED,
                       TORRENT_PAUSED,
                       TORRENT_RESUMED,
                       TORRENT_CHECKED,
                       URL_SEED,
                       FILE_ERROR,
                       METADATA_FAILED,
                       METADATA_RECEIVED,
                       UDP_ERROR,
                       EXTERNAL_IP,
                       LISTEN_FAILED,
                       LISTEN_SUCCEEDED,
                       PORTMAP_ERROR,
                       PORTMAP,
                       PORTMAP_LOG,
                       FASTRESUME_REJECTED,
                       PEER_BLOCKED,
                       DHT_ANNOUNCE,
                       DHT_GET_PEERS,
                       STATS,
                       CACHE_FLUSHED,
                       ANONYMOUS_MODE,
                       LSD_PEER,
                       TRACKERID,
                       DHT_BOOTSTRAP,
                       UNKNOWN,
                       TORRENT_ERROR,
                       TORRENT_NEED_CERT,
                       INCOMING_CONNECTION,
                       ADD_TORRENT,
                       STATE_UPDATE,
                       MMAP_CACHE,
                       SESSION_STATS,
                       TORRENT_UPDATE,
                       UNKNOWN,
                       DHT_ERROR,
                       DHT_IMMUTABLE_ITEM,
                       DHT_MUTABLE_ITEM,
                       DHT_PUT,
                       I2P,
                       DHT_OUTGOING_GET_PEERS,
                       LOG,
                       TORRENT_LOG,
                       PEER_LOG,
                       LSD_ERROR,
                       DHT_STATS,
                       INCOMING_REQUEST,
                       DHT_LOG,
                       DHT_PKT,
                       DHT_GET_PEERS_REPLY,
                       DHT_DIRECT_RESPONSE,
                       PICKER_LOG };

    AlertType(int swigValue) {
        this.swigValue = swigValue;
    }

    private final int swigValue;

    public int getSwig() {
        return swigValue;
    }

    public static AlertType fromSwig(int swigValue) {
        try {
            return ALERT_TYPES[swigValue];
        } catch (RuntimeException e) {
	    return UNKNOWN;
	}
    }
}
