/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class dht_get_peers_reply_alert extends alert {
  private transient long swigCPtr;

  protected dht_get_peers_reply_alert(long cPtr, boolean cMemoryOwn) {
    super(libtorrent_jni.dht_get_peers_reply_alert_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dht_get_peers_reply_alert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(dht_get_peers_reply_alert obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_dht_get_peers_reply_alert(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int type() {
    return libtorrent_jni.dht_get_peers_reply_alert_type(swigCPtr, this);
  }

  public alert_category_t category() {
    return new alert_category_t(libtorrent_jni.dht_get_peers_reply_alert_category(swigCPtr, this), true);
  }

  public String what() {
    return libtorrent_jni.dht_get_peers_reply_alert_what(swigCPtr, this);
  }

  public String message() {
    return libtorrent_jni.dht_get_peers_reply_alert_message(swigCPtr, this);
  }

  public void setInfo_hash(SWIGTYPE_p_sha1_hash value) {
    libtorrent_jni.dht_get_peers_reply_alert_info_hash_set(swigCPtr, this, SWIGTYPE_p_sha1_hash.getCPtr(value));
  }

  public SWIGTYPE_p_sha1_hash getInfo_hash() {
    return new SWIGTYPE_p_sha1_hash(libtorrent_jni.dht_get_peers_reply_alert_info_hash_get(swigCPtr, this), true);
  }

  public int num_peers() {
    return libtorrent_jni.dht_get_peers_reply_alert_num_peers(swigCPtr, this);
  }

  public tcp_endpoint_vector peers() {
    return new tcp_endpoint_vector(libtorrent_jni.dht_get_peers_reply_alert_peers(swigCPtr, this), true);
  }

  public final static alert_category_t static_category = new alert_category_t(libtorrent_jni.dht_get_peers_reply_alert_static_category_get(), false);
  public final static alert_priority priority = alert_priority.swigToEnum(libtorrent_jni.dht_get_peers_reply_alert_priority_get());
  public final static int alert_type = libtorrent_jni.dht_get_peers_reply_alert_alert_type_get();
}
