/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public interface libtorrentConstants {
  public final static int BOOST_VERSION = libtorrent_jni.BOOST_VERSION_get();
  public final static String BOOST_LIB_VERSION = libtorrent_jni.BOOST_LIB_VERSION_get();
  public final static int LIBTORRENT_VERSION_MAJOR = libtorrent_jni.LIBTORRENT_VERSION_MAJOR_get();
  public final static int LIBTORRENT_VERSION_MINOR = libtorrent_jni.LIBTORRENT_VERSION_MINOR_get();
  public final static int LIBTORRENT_VERSION_TINY = libtorrent_jni.LIBTORRENT_VERSION_TINY_get();
  public final static int LIBTORRENT_VERSION_NUM = libtorrent_jni.LIBTORRENT_VERSION_NUM_get();
  public final static String LIBTORRENT_VERSION = libtorrent_jni.LIBTORRENT_VERSION_get();
  public final static String LIBTORRENT_REVISION = libtorrent_jni.LIBTORRENT_REVISION_get();
  public final static int tracker_retry_delay_min = libtorrent_jni.tracker_retry_delay_min_get();
  public final static int tracker_retry_delay_max = libtorrent_jni.tracker_retry_delay_max_get();

  public final static int TORRENT_MAX_ALERT_TYPES = libtorrent_jni.TORRENT_MAX_ALERT_TYPES_get();
  public final static int num_alert_types = libtorrent_jni.num_alert_types_get();

  public final static int TORRENT_ALERT_MANAGER_MAX_ARITY = libtorrent_jni.TORRENT_ALERT_MANAGER_MAX_ARITY_get();
  public final static int TORRENT_DEBUG_STREAMING = libtorrent_jni.TORRENT_DEBUG_STREAMING_get();
  public final static int CCONTROL_TARGET = libtorrent_jni.CCONTROL_TARGET_get();
  public final static int TORRENT_UTP_LOG = libtorrent_jni.TORRENT_UTP_LOG_get();
  public final static int TORRENT_VERBOSE_UTP_LOG = libtorrent_jni.TORRENT_VERBOSE_UTP_LOG_get();
  public final static int TORRENT_IPV4_HEADER = libtorrent_jni.TORRENT_IPV4_HEADER_get();
  public final static int TORRENT_IPV6_HEADER = libtorrent_jni.TORRENT_IPV6_HEADER_get();
  public final static int TORRENT_UDP_HEADER = libtorrent_jni.TORRENT_UDP_HEADER_get();
  public final static int TORRENT_SOCKS5_HEADER = libtorrent_jni.TORRENT_SOCKS5_HEADER_get();
  public final static int TORRENT_ETHERNET_MTU = libtorrent_jni.TORRENT_ETHERNET_MTU_get();
  public final static int TORRENT_TEREDO_MTU = libtorrent_jni.TORRENT_TEREDO_MTU_get();
  public final static int TORRENT_INET_MIN_MTU = libtorrent_jni.TORRENT_INET_MIN_MTU_get();
  public final static int TORRENT_INET_MAX_MTU = libtorrent_jni.TORRENT_INET_MAX_MTU_get();

  public final static String LIBTORRENT_REVISION_SHA1 = libtorrent_jni.LIBTORRENT_REVISION_SHA1_get();
  public final static String JLIBTORRENT_REVISION_SHA1 = libtorrent_jni.JLIBTORRENT_REVISION_SHA1_get();
}
