/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class partial_piece_info_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected partial_piece_info_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(partial_piece_info_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(partial_piece_info_vector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_partial_piece_info_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public partial_piece_info_vector() {
    this(libtorrent_jni.new_partial_piece_info_vector(), true);
  }

  public long size() {
    return libtorrent_jni.partial_piece_info_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return libtorrent_jni.partial_piece_info_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtorrent_jni.partial_piece_info_vector_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return libtorrent_jni.partial_piece_info_vector_empty(swigCPtr, this);
  }

  public void clear() {
    libtorrent_jni.partial_piece_info_vector_clear(swigCPtr, this);
  }

  public void push_back(partial_piece_info x) {
    libtorrent_jni.partial_piece_info_vector_push_back(swigCPtr, this, partial_piece_info.getCPtr(x), x);
  }

  public partial_piece_info get(int i) {
    return new partial_piece_info(libtorrent_jni.partial_piece_info_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, partial_piece_info val) {
    libtorrent_jni.partial_piece_info_vector_set(swigCPtr, this, i, partial_piece_info.getCPtr(val), val);
  }

}
