/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class piece_index_bitfield {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected piece_index_bitfield(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(piece_index_bitfield obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_piece_index_bitfield(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean get_bit(int index) {
    return libtorrent_jni.piece_index_bitfield_get_bit(swigCPtr, this, index);
  }

  public void clear_bit(int index) {
    libtorrent_jni.piece_index_bitfield_clear_bit(swigCPtr, this, index);
  }

  public void set_bit(int index) {
    libtorrent_jni.piece_index_bitfield_set_bit(swigCPtr, this, index);
  }

  public int end_index() {
    return libtorrent_jni.piece_index_bitfield_end_index(swigCPtr, this);
  }

  public piece_index_bitfield() {
    this(libtorrent_jni.new_piece_index_bitfield(), true);
  }

}
