/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class piece_index_int_pair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected piece_index_int_pair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(piece_index_int_pair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_piece_index_int_pair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public piece_index_int_pair() {
    this(libtorrent_jni.new_piece_index_int_pair__SWIG_0(), true);
  }

  public piece_index_int_pair(int first, int second) {
    this(libtorrent_jni.new_piece_index_int_pair__SWIG_1(first, second), true);
  }

  public piece_index_int_pair(piece_index_int_pair other) {
    this(libtorrent_jni.new_piece_index_int_pair__SWIG_2(piece_index_int_pair.getCPtr(other), other), true);
  }

  public void setFirst(int value) {
    libtorrent_jni.piece_index_int_pair_first_set(swigCPtr, this, value);
  }

  public int getFirst() {
    return libtorrent_jni.piece_index_int_pair_first_get(swigCPtr, this);
  }

  public void setSecond(int value) {
    libtorrent_jni.piece_index_int_pair_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return libtorrent_jni.piece_index_int_pair_second_get(swigCPtr, this);
  }

}
