/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class port_mapping_t_vector extends java.util.AbstractList<int> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected port_mapping_t_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(port_mapping_t_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(port_mapping_t_vector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_port_mapping_t_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public port_mapping_t_vector(int[] initialElements) {
    this();
    reserve(initialElements.length);

    for (int element : initialElements) {
      add(element);
    }
  }

  public port_mapping_t_vector(Iterable<int> initialElements) {
    this();
    for (int element : initialElements) {
      add(element);
    }
  }

  public int get(int index) {
    return doGet(index);
  }

  public int set(int index, int e) {
    return doSet(index, e);
  }

  public boolean add(int e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, int e) {
    modCount++;
    doAdd(index, e);
  }

  public int remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public port_mapping_t_vector() {
    this(libtorrent_jni.new_port_mapping_t_vector__SWIG_0(), true);
  }

  public port_mapping_t_vector(port_mapping_t_vector other) {
    this(libtorrent_jni.new_port_mapping_t_vector__SWIG_1(port_mapping_t_vector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libtorrent_jni.port_mapping_t_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtorrent_jni.port_mapping_t_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtorrent_jni.port_mapping_t_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtorrent_jni.port_mapping_t_vector_clear(swigCPtr, this);
  }

  public port_mapping_t_vector(int count, int value) {
    this(libtorrent_jni.new_port_mapping_t_vector__SWIG_2(count, value), true);
  }

  private int doSize() {
    return libtorrent_jni.port_mapping_t_vector_doSize(swigCPtr, this);
  }

  private void doAdd(int x) {
    libtorrent_jni.port_mapping_t_vector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, int x) {
    libtorrent_jni.port_mapping_t_vector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private int doRemove(int index) {
    return libtorrent_jni.port_mapping_t_vector_doRemove(swigCPtr, this, index);
  }

  private int doGet(int index) {
    return libtorrent_jni.port_mapping_t_vector_doGet(swigCPtr, this, index);
  }

  private int doSet(int index, int val) {
    return libtorrent_jni.port_mapping_t_vector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libtorrent_jni.port_mapping_t_vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
