/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class SWIGTYPE_p_flags__bitfield_flagT_std__uint8_t_libtorrent__file_flags_tag_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_flags__bitfield_flagT_std__uint8_t_libtorrent__file_flags_tag_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_flags__bitfield_flagT_std__uint8_t_libtorrent__file_flags_tag_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_flags__bitfield_flagT_std__uint8_t_libtorrent__file_flags_tag_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_flags__bitfield_flagT_std__uint8_t_libtorrent__file_flags_tag_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

