/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public class tracker_connection {
  private long swigCPtr;
  private boolean swigCMemOwnBase;

  protected tracker_connection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tracker_connection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwnBase) {
      swigCMemOwnBase = false;
      libtorrent_jni.delete_tracker_connection(swigCPtr);
    }
    swigCPtr = 0;
  }

  public tracker_request tracker_req() {
    return new tracker_request(libtorrent_jni.tracker_connection_tracker_req(swigCPtr, this), false);
  }

  public void fail(error_code ec, int code, String msg, int interval, int min_interval) {
    libtorrent_jni.tracker_connection_fail__SWIG_0(swigCPtr, this, error_code.getCPtr(ec), ec, code, msg, interval, min_interval);
  }

  public void fail(error_code ec, int code, String msg, int interval) {
    libtorrent_jni.tracker_connection_fail__SWIG_1(swigCPtr, this, error_code.getCPtr(ec), ec, code, msg, interval);
  }

  public void fail(error_code ec, int code, String msg) {
    libtorrent_jni.tracker_connection_fail__SWIG_2(swigCPtr, this, error_code.getCPtr(ec), ec, code, msg);
  }

  public void fail(error_code ec, int code) {
    libtorrent_jni.tracker_connection_fail__SWIG_3(swigCPtr, this, error_code.getCPtr(ec), ec, code);
  }

  public void fail(error_code ec) {
    libtorrent_jni.tracker_connection_fail__SWIG_4(swigCPtr, this, error_code.getCPtr(ec), ec);
  }

  public void start() {
    libtorrent_jni.tracker_connection_start(swigCPtr, this);
  }

  public void close() {
    libtorrent_jni.tracker_connection_close(swigCPtr, this);
  }

  public address bind_interface() {
    return new address(libtorrent_jni.tracker_connection_bind_interface(swigCPtr, this), false);
  }

  public void sent_bytes(int bytes) {
    libtorrent_jni.tracker_connection_sent_bytes(swigCPtr, this, bytes);
  }

  public void received_bytes(int bytes) {
    libtorrent_jni.tracker_connection_received_bytes(swigCPtr, this, bytes);
  }

  public boolean on_receive_hostname(error_code arg0, String arg1, String arg2, int arg3) {
    return libtorrent_jni.tracker_connection_on_receive_hostname(swigCPtr, this, error_code.getCPtr(arg0), arg0, arg1, arg2, arg3);
  }

  public tracker_connection shared_from_this() {
    long cPtr = libtorrent_jni.tracker_connection_shared_from_this(swigCPtr, this);
    return (cPtr == 0) ? null : new tracker_connection(cPtr, true);
  }

}
