/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.frostwire.jlibtorrent.swig;

public enum utp_extensions_t {
  utp_no_extension(libtorrent_jni.utp_no_extension_get()),
  utp_sack(libtorrent_jni.utp_sack_get()),
  utp_close_reason(libtorrent_jni.utp_close_reason_get());

  public final int swigValue() {
    return swigValue;
  }

  public static utp_extensions_t swigToEnum(int swigValue) {
    utp_extensions_t[] swigValues = utp_extensions_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (utp_extensions_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + utp_extensions_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private utp_extensions_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private utp_extensions_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private utp_extensions_t(utp_extensions_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

